### ISSUE TITLE
⭐ [Feature] : 백엔드 응답 객체 (ResponseDTO) 추가 구현

### ISSUE THREAD

**Issue by programofktw** [KGU-TurtleDoctor/POKEMEDI-Server#10]
## 💚 어떤 기능인가요?
프론트 요청에 대해 백엔드가 같은 틀로 보내기 위한 객체의 구현
요청 성공 여부와 상태코드, 핵심 객체들이 포함되어 있을 예정 

## ✅ To-Do
- [ ] ResponseDTO에 들어갈 속성 정의
- [ ] 응답 Json 형식 결정
- [ ] ResponseDTO 객체 class 제작

## 🍧 ETC
