### ISSUE TITLE
⭐ [Feature] : OpenAi Api 기능에 Entity 활용하여 챗봇 서비스 기능 개발 

### ISSUE THREAD

**Issue by programofktw** [KGU-TurtleDoctor/POKEMEDI-Server#18]
## 💚 어떤 기능인가요?
OpenAi Api에 Entity와 상호작용 하며 사용자가 챗봇을 이용할 때 
질문에 대한 응답과 해당 대화를 저장하는 기능. 

## ✅ To-Do

- [ ] 최초 채팅시 ChatHistory 만들어서 Front에 전송.
- [ ] 사용자의 채팅에 따른 응답 제공
- [ ] 최초 채팅을 제외한 모든 채팅 요청에는 ChatHistoryId가 있어야함.
- [ ] 각 채팅마다 해당 내용을 DB에 저장.
- [ ] ChatHistoryId 를 통해서 채팅 내역 불러오기
