### ISSUE TITLE
⭐ [Feature] : openai api 연동(gpt에게 응답 받기 까지)

### ISSUE THREAD

**Issue by programofktw** [KGU-TurtleDoctor/POKEMEDI-Server#5]
## 💚 어떤 기능인가요?

openai api를 이용한 GPT 모델로부토 질문을 전달하고 응답을 받아오는 것까지

## ✅ To-Do

- [ ] Get OR Post 방식으로 질문을 받기.
- [ ] openai  api으로 질문 전송
- [ ] openai api로부터 응답 수신
