### ISSUE TITLE
⭐ [Feature] : ChatBot Script 방식 API 구현

### ISSUE THREAD

**Issue by programofktw** [KGU-TurtleDoctor/POKEMEDI-Server#9]
## 💚 어떤 기능인가요?
OpenAi api 거치지 않고 즉시 반환하는 챗봇 채팅에 대한 api 호출 처리
 ex) 챗봇 페이지 최초 접속 시 그에 대한 환영 인사 및 카테고리 전달
## ✅ To-Do
- [ ] Script로 작동하는 Controller와 Service 추가
- [ ] script가 DB에 저장되는 경우 그에 따른 Entity 및 Repository 추가
- [ ] 백엔드 api 호출시 반환될 DTO 제작
